{% set name = "mkdocs-jupyter" %}
{% set version = "0.17.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocs-jupyter-{{ version }}.tar.gz
  sha256: e9a858f79f2cdd71a2558c3b51787663361ec258e1f709c19aa19e8be9582fa7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
    - poetry
  run:
    - mkdocs >=1.1.0
    - nbconvert >=6.0.7,<7
    - python >=3.7
    - jupytext >=1.11.0
    - mkdocs-material >=7.2.8

test:
  imports:
    - mkdocs_jupyter
    - mkdocs_jupyter.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/danielfrg/mkdocs-jupyter
  summary: Use Jupyter Notebooks in mkdocs
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hadim
