{% set name = "mkdocs-jupyter" %}
{% set version = "0.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e26c1d341916bc57f96ea3f93d8d0a88fc77c87d4cee222f66d2007798d924f5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - hatch >=1
  run:
    - python >=3.8
    - nbconvert <8,>=7.2.9
    - mkdocs <2,>=1.4.0
    - mkdocs-material >9.0.0
    - jupytext <2,>1.13.8
    - pygments >2.12.0
    - ipykernel <7.0.0,>6.0.0

test:
  imports:
    - mkdocs_jupyter
    - mkdocs_jupyter.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/danielfrg/mkdocs-jupyter
  summary: Use Jupyter Notebooks in mkdocs
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - cpcloud
    - cwognum
