{% set name = "mkdocs-jupyter" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocs-jupyter-{{ version }}.tar.gz
  sha256: c8c00ce44456e3cf50c5dc3fe0cb18fab6467fb5bafc2c0bfe1efff3e0a52470

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - poetry-core >=1
    - setuptools >=57,<58
  run:
    - mkdocs >=1.2.3
    - nbconvert >=6.2,<7
    - python >=3.7
    - jupytext >=1.13.8
    - mkdocs-material >=8.0.0
    - pygments >=2.12.0

test:
  imports:
    - mkdocs_jupyter
    - mkdocs_jupyter.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/danielfrg/mkdocs-jupyter
  summary: Use Jupyter Notebooks in mkdocs
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hadim
    - cpcloud
